--autogenerated by gmodhaxe. Do not touch!
AddCSLuaFile("cl_init.lua") 
for i,p in pairs(@(exportName).@(genName).properties) do
    @(baseIdent)[i] = p
end
@if(sent()) {
@(baseIdent).Type = "@entLuaType"}

@if(sentSwep()) {
@if(client) {
function @(baseIdent):Think()
    if (not self._gHaxeInit) then
        self:Initalize()
    end
    @if (overridenThink)
    {self._gHaxeBurrow:Think()}
end }
function @(baseIdent):Initialize()
    local ent = @(exportName).@(genName).new(self)
    self._gHaxeBurrow = ent
    @if (overridenInit)
    {self._gHaxeBurrow:Initialize()}
    @if (client)
    {self._gHaxeInit = true}
end
} else {
function @(baseIdent):Init(...)
    local ent = @(exportName).@(genName).new(self)
    self._gHaxeBurrow = ent
    @if (overridenInit)
    {self._gHaxeBurrow:Init(...)}
end
}

@for(field in funcs) {
@if(shouldAdd(field)) {
function @(baseIdent):@(field.name)(...)
    self._gHaxeBurrow.@(field.name)(...)
end
}
}