--autogenerated by gmodhaxe. Do not touch!
AddCSLuaFile("cl_init.lua")
::if sentSwep:: 
::baseIdent::.Base = "::base::" ::end::
for i,p in pairs(::exportName::.::genName::.properties) do
    ::baseIdent::[i] = p
end
::if sent::
::baseIdent::.Type = "::entLuaType::" ::end::

::if sentSwep:: 
::if client:: 
function ::baseIdent:::Think()
    if (not self._gHaxeInit) then
        self:Initalize()
    end
    ::if overridenThink::
    self._gHaxeBurrow:Think() ::end::
end::end::
function ::baseIdent:::Initialize()
    local ent = ::exportName::.::genName::.new(self)
    self._gHaxeBurrow = ent
    ::if overridenInit::
    self._gHaxeBurrow:Initialize() ::end::
    ::if client::
    self._gHaxeInit = true ::end::
end
::else::
function ::baseIdent:::Init(...)
    local ent = @(exportName).@(genName).new(self)
    self._gHaxeBurrow = ent
    ::if overridenInit::
    self._gHaxeBurrow:Init(...)::end::
end
::end::

::foreach funcs::
::if shouldAdd:: 
function ::baseIdent:::::name::(...)
    self._gHaxeBurrow.::name::(...)
end
::end::
::end::